- name: install supervisor
  apt: cache_valid_time={{ apt_cache_seconds }}
       name=supervisor
       state=latest
       update_cache=yes
  become: true

- name: add supervisor configuration file for gunicorn
  template: src=supervisor-gunicorn.conf
            dest=/etc/supervisor/conf.d/gunicorn.conf
  become: true
  notify:
    - restart gunicorn

- name: database migrate
  django_manage: command=migrate
                 app_path={{ srv_directory }}
                 settings={{ project_name }}.settings.{{ environment_type }}
                 virtualenv={{ virtualenv_folder_root }}/current
  notify:
    - restart gunicorn

- name: collect static files
  django_manage: command=collectstatic
                 app_path={{ srv_directory }}
                 settings={{ project_name }}.settings.{{ environment_type }}
                 virtualenv={{ virtualenv_folder_root }}/current
  notify:
    - restart nginx
